project:
  type: default
  render:
    - 1-monge-kantorovich/index.qmd
    - 2-entropic-regularization/index.qmd
    - 3-dual-semidiscrete/index.qmd
    - 4-dynamic-flows/index.qmd

execute:
  freeze: auto

